window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: JetBrains Mono

  size: 12

  offset:
    x: -1
    y: 0

# Colors (Pencil Light)
colors:
  # Default Colors
  primary:
    background: "#f1f1f1"
    foreground: "#424242"
  # Normal colors
  normal:
    black: "#212121"
    red: "#fb007a"
    green: "#5fd7af"
    yellow: "#f3e430"
    blue: "#20bbfc"
    magenta: "#6855de"
    cyan: "#4fb8cc"
    white: "#ffffff"
  # Bright colors
  bright:
    black: "#212121"
    red: "#fb007a"
    green: "#5fd7af"
    yellow: "#f3e430"
    blue: "#20bbfc"
    magenta: "#6855de"
    cyan: "#4fb8cc"
    white: "#ffffff"
  dim:
    black: "#212121"
    red: "#c30771"
    green: "#10a778"
    yellow: "#a89c14"
    blue: "#008ec4"
    magenta: "#523c79"
    cyan: "#20a5ba"
    white: "#e0e0e0"
