window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: JetBrainsMono Nerd Font

  size: 12

colors:
  # Default colors
  primary:
    # hard contrast: background = '0xf9f5d7'
    background: "0x322931"
    # soft contrast: background = '0xf2e5bc'
    foreground: "0xb9b5b8"

  # Normal colors
  normal:
    black: "0xfffde6"
    red: "0xfc332b"
    green: "0x8fc13e"
    yellow: "0xfdcb23"
    blue: "0x1290bf"
    magenta: "0xfc608a"
    cyan: "0x19988b"
    white: "0x171015"

  # Bright colors
  bright:
    black: "0xffffff"
    red: "0xfd948c"
    green: "0x5fdba7"
    yellow: "0xfed46b"
    blue: "0x829bd6"
    magenta: "0x8f3f71"
    cyan: "0x1ac9bf"
    white: "0x171015"
