layer: top
reload_style_on_change: true
include:
  - ~/.cache/waybar/position.json
  - ~/.config/waybar/modules.json
modules-left:
  - hyprland/submap
  - hyprland/window
modules-center:
  - hyprland/workspaces
modules-right:
  - group/expand
  - pulseaudio
  - network
  - idle_inhibitor
  - custom/sunset
  - clock
  - battery
  - tray
hyprland/workspaces:
  format: '{icon}'
  format-icons:
    '1': 
    '2': 
    '3': 
    '4': 
    '5': 
    '6': 
    '7': 
    '8': 
    '9': 
    '10': 
    active: 
    default: 
    empty: 
  persistent-workspaces:
    '*':
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
group/expand:
  orientation: horizontal
  drawer:
    transition-duration: 600
    transition-to-left: true
    click-to-reveal: true
  modules:
    - custom/expand
    - cpu
    - memory
    - temperature
    - backlight
    - custom/endpoint
