font_size: 22
theme: pywal
banner: "/home/anne/dotfiles/StartTree/dot-config/StartTree/banners"
tree_1:
  general:
    gmail: "https://mail.google.com/"
    youtube: "https://www.youtube.com/"
    wttr: "https://wttr.in/"
  social:
    reddit: "https://www.reddit.com/"
    unixporn: "https://www.reddit.com/r/unixporn/"
    twitter: "https://x.com"
tree_2:
  dev:
    github: "https://www.github.com/"
    nextjs: "https://nextjs.org/"
  sys:
    archwiki: 
      - "https://archlinux.org/"
      - "arch wiki"
    freebsd: "https://www.freebsd.org/"
    hyprland: "https://wiki.hyprland.org/" 
    qute: "https://raw.githubusercontent.com/qutebrowser/qutebrowser/main/doc/img/cheatsheet-big.png"
    tmux: "https://devhints.io/tmux"
tree_3:
  transit:
    caliblue: "https://www.transitchicago.com/traintracker/arrivaltimes/?sid=40570"
    divblue: "https://www.transitchicago.com/traintracker/arrivaltimes/?sid=40320"
    cal@ful -> s: "https://ctabustracker.com/predictions/bystop/bustime:17042"
    cal@wal -> n: "https://ctabustracker.com/predictions/bystop/bustime:17153"
    ful@cal -> e: "https://ctabustracker.com/predictions/bystop/bustime:1329"


